apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2022-09-13T08:49:21Z"
  generation: 4
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  uid: 18a18296-c8e8-4efa-ade1-409974c50112
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-09-13T16:19:12+07:00"
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: nginx-1-config-ftzx
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: nginx-1-config-ftzx
          image: us-central1-docker.pkg.dev/mrmurazza-sandbox/dealljobs-test/docker-dealljobs-test:1.0.1-amd64
          imagePullPolicy: IfNotPresent
          name: docker-dealljobs-test-sha256-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30